class ContasNomesConfig {
  /// Retorna o mapeamento de nomes das contas no idioma especificado
  static Map<String, String> getNomesContas(String languageCode) {
    switch (languageCode) {
      case 'pt':
        return {
          // ATIVOS
          'ativo': 'Ativo',
          'ativoCirculante': 'Ativo Circulante',
          'disponivel': 'Disponível',
          'caixa': 'Caixa',
          'bancos': 'Bancos',
          // Novo: nome para a subconta de cada banco em Ativos (Conta Corrente)
          'bancos_contaCorrente': 'Conta Corrente',
          'aplicacoes': 'Aplicações Financeiras',
          'direitosRealizaveis': 'Direitos Realizáveis',
          'clientes': 'Clientes',
          'adiantamentos': 'Adiantamentos',
          'impostosRecuperar': 'Impostos a Recuperar',
          'estoques': 'Estoques',
          'estoqueInsumos': 'Estoque de Insumos',
          'estoqueSementes': 'Estoque de Sementes',
          'estoqueDefensivos': 'Estoque de Defensivos',
          'estoqueFertilizantes': 'Estoque de Fertilizantes',
          'estoqueEmbalagens': 'Estoque de Embalagens',
          'estoqueProducao': 'Estoque de Produção',
          'ativoNaoCirculante': 'Ativo Não Circulante',
          'realizavelLongoPrazo': 'Realizável a Longo Prazo',
          'investimentos': 'Investimentos',
          'imobilizado': 'Imobilizado',
          'maquinasEquipamentos': 'Máquinas e Equipamentos',
          'veiculos': 'Veículos',
          'instalacoes': 'Instalações',
          'terras': 'Terras',
          'culturasPermanentes': 'Culturas Permanentes',
          'ativosBiologicos': 'Ativos Biológicos',
          'gado': 'Gado',
          'florestas': 'Florestas',
          'licencasAmbientais': 'Licenças Ambientais',
          'direitosExploracaoAgricola': 'Direitos de Exploração Agrícola',

          // PASSIVOS
          'passivo': 'Passivo',
          'passivoCirculante': 'Passivo Circulante',
          'fornecedores': 'Fornecedores',
          'emprestimosFinanciamentos': 'Empréstimos e Financiamentos',
          // Novos: para cada banco, dentro de EMPRESTIMOS_FINANCIAMENTOS,
          // serão criadas duas subcontas:
          'emprestimos_sub_financiamentos': 'Empréstimos e Financiamentos',
          'emprestimos_sub_cartao': 'Cartão de Crédito',
          'obrigacoesTrabalhistas': 'Obrigações Trabalhistas',
          'obrigacoesTributarias': 'Obrigações Tributárias',
          'adiantamentosClientes': 'Adiantamentos de Clientes',
          'passivoNaoCirculante': 'Passivo Não Circulante',
          'emprestimosLp': 'Empréstimos a Longo Prazo',
          'financiamentosLp': 'Financiamentos a Longo Prazo',
          'emprestimosLP': 'Empréstimos a Longo Prazo',
          'financiamentosLP': 'Financiamentos a Longo Prazo',
          'financiamentosRurais': 'Financiamentos Rurais',
          'pronaf': 'PRONAF',
          'dividasArmazens': 'Dívidas com Armazéns',

          // RECEITAS
          'receitas': 'Receitas',
          'receitasOperacionais': 'Receitas Operacionais',
          'receitasProdutosAgricolas': 'Receitas de Produtos Agrícolas',
          'receitasProdutosPecuarios': 'Receitas de Produtos Pecuários',
          'subsidiosGovernamentais': 'Subsídios Governamentais',
          'prestacaoServicos': 'Prestação de Serviços',
          'outrasReceitas': 'Outras Receitas',
          'receitasFinanceiras': 'Receitas Financeiras',
          'receitasEventuais': 'Receitas Eventuais',

          // CUSTOS E DESPESAS
          'custos': 'Custos',
          'custosProducao': 'Custos de Produção',
          'custosAtividadesAgricolas': 'Custos de Atividades Agrícolas',
          'custosAtividadesPecuarias': 'Custos de Atividades Pecuárias',
          'custosArmazenamento': 'Custos de Armazenamento',
          'custosTransporte': 'Custos de Transporte',
          'custosIndiretos': 'Custos Indiretos',
          'manutencao': 'Manutenção',
          'maoObraIndireta': 'Mão de Obra Indireta',
          'energiaCombustiveis': 'Energia e Combustíveis',
          'fretes': 'Fretes',
          'despesas': 'Despesas',
          'despesasAdministrativas': 'Despesas Administrativas',
          'despesasComerciais': 'Despesas Comerciais',
          'despesasFinanceiras': 'Despesas Financeiras',
          'despesasTributarias': 'Despesas Tributárias',

          // CONTAS DE APURAÇÃO
          'contasApuracao': 'Contas de Apuração',
          'apuracaoResultado': 'Apuração do Resultado',
          'culturasFormacao': 'Culturas em Formação',
        };
      default:
        return {
          // ATIVOS
          'ativo': 'Assets',
          'ativoCirculante': 'Current Assets',
          'disponivel': 'Available',
          'caixa': 'Cash',
          'bancos': 'Banks',
          // Novo: nome para a subconta de cada bank (Checking Account)
          'bancos_contaCorrente': 'Checking Account',
          'aplicacoes': 'Financial Investments',
          'direitosRealizaveis': 'Receivables',
          'clientes': 'Customers',
          'adiantamentos': 'Advances',
          'impostosRecuperar': 'Recoverable Taxes',
          'estoques': 'Inventory',
          'estoqueInsumos': 'Input Inventory',
          'estoqueSementes': 'Seed Inventory',
          'estoqueDefensivos': 'Pesticide Inventory',
          'estoqueFertilizantes': 'Fertilizer Inventory',
          'estoqueEmbalagens': 'Packaging Inventory',
          'estoqueProducao': 'Production Inventory',
          'ativoNaoCirculante': 'Non-Current Assets',
          'realizavelLongoPrazo': 'Long-term Receivables',
          'investimentos': 'Investments',
          'imobilizado': 'Fixed Assets',
          'maquinasEquipamentos': 'Machinery and Equipment',
          'veiculos': 'Vehicles',
          'instalacoes': 'Facilities',
          'terras': 'Land',
          'culturasPermanentes': 'Permanent Crops',
          'ativosBiologicos': 'Biological Assets',
          'gado': 'Cattle',
          'florestas': 'Forests',
          'licencasAmbientais': 'Environmental Licenses',
          'direitosExploracaoAgricola': 'Agricultural Exploration Rights',

          // LIABILITIES
          'passivo': 'Liabilities',
          'passivoCirculante': 'Current Liabilities',
          'fornecedores': 'Suppliers',
          'emprestimosFinanciamentos': 'Loans and Financing',
          // Novos para subaccounts em Loans/Financing:
          'emprestimos_sub_financiamentos': 'Loans and Financing',
          'emprestimos_sub_cartao': 'Credit Card',
          'obrigacoesTrabalhistas': 'Labor Obligations',
          'obrigacoesTributarias': 'Tax Obligations',
          'adiantamentosClientes': 'Customer Advances',
          'passivoNaoCirculante': 'Non-Current Liabilities',
          'emprestimosLp': 'Long-term Loans',
          'financiamentosLp': 'Long-term Financing',
          'emprestimosLP': 'Long-term Loans',
          'financiamentosLP': 'Long-term Financing',
          'financiamentosRurais': 'Rural Financing',
          'pronaf': 'PRONAF',
          'dividasArmazens': 'Warehouse Debts',

          // REVENUE
          'receitas': 'Revenue',
          'receitasOperacionais': 'Operating Revenue',
          'receitasProdutosAgricolas': 'Agricultural Products Revenue',
          'receitasProdutosPecuarios': 'Livestock Products Revenue',
          'subsidiosGovernamentais': 'Government Subsidies',
          'prestacaoServicos': 'Service Revenue',
          'outrasReceitas': 'Other Revenue',
          'receitasFinanceiras': 'Financial Revenue',
          'receitasEventuais': 'Miscellaneous Revenue',

          // COSTS AND EXPENSES
          'custos': 'Costs',
          'custosProducao': 'Production Costs',
          'custosAtividadesAgricolas': 'Agricultural Activities Costs',
          'custosAtividadesPecuarias': 'Livestock Activities Costs',
          'custosArmazenamento': 'Storage Costs',
          'custosTransporte': 'Transportation Costs',
          'custosIndiretos': 'Indirect Costs',
          'manutencao': 'Maintenance',
          'maoObraIndireta': 'Indirect Labor',
          'energiaCombustiveis': 'Energy and Fuel',
          'fretes': 'Freight',
          'despesas': 'Expenses',
          'despesasAdministrativas': 'Administrative Expenses',
          'despesasComerciais': 'Commercial Expenses',
          'despesasFinanceiras': 'Financial Expenses',
          'despesasTributarias': 'Tax Expenses',

          // SETTLEMENT ACCOUNTS
          'contasApuracao': 'Settlement Accounts',
          'apuracaoResultado': 'Income Statement',
          'culturasFormacao': 'Developing Crops',
        };
    }
  }
}
