/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData inseticida = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cesta_cereais = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carriola_legumes_2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adubacao_manual = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chuva_campo = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData armazem_silo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData galao_defensivo = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adubo_liquido = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulverizacao_manual = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adubacao_manual_bold = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adubo_liquido_bold = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saco_semente_preto = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adubo_organico = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inseticida_bold = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulverizacao_manual_2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulverizacao_area_bold = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_semente = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adubo_liquido_bold_2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_semente_2 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulverizacao_drone = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_semente_bold = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_semente_bold_2 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agricultura_varios = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saco_semente = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caixa_legumes_2 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_campo_2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agriculture = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cattle = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cattle_2 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cattle_3 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cattle_4 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cattle_5 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken_2 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken_3 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crops = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken_4 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crops_2 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farming_time = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farming_time_bold = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData field = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData field_2 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData field_with_harvest = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grain = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData harvest = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData harvest_2 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pig = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pig_2 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planting = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rooster = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rubber_tapper = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rubber_tapper_2 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rubber_tree = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rubber_tree_2 = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soy = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sugar_cane_2 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caixa_legumes = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData garrafa_laranja = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cesta_legumes = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carriola_legumes = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_campo = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cesta_frutas = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plantio_manual_bold = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_cultivo_2 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_barracao = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_operacao = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_cultivo = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plantio_manual_bold_3 = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cultivo_manual_3 = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cultivo_manual_4 = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_cultivo_4 = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mao_na_planta_3 = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engrenagem_chave_operacao = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engrenagem = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_operacao_5 = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cultivo_manual_2 = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_campo_3 = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_campo_4 = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plantio_manual_bold_2 = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mao_na_planta = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plantas_sol_nuvem = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cultivo_manual = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mao_na_planta_2 = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_cultivo_3 = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_operacao_4 = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_barracao_2 = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_operacao_3 = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_operacao_2 = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_no_quadro = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_bonito = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trator_pessoa = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
