class Permissions {
  static const Map<String, Map<String, Map<String, bool>>> roles = <String, Map<String, Map<String, bool>>>{
    'Admin': <String, Map<String, bool>>{
      'produtores': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'propriedades': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'talhoes': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'itens': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'pessoas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'compras': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosChuvas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'bancos': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosColetas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosEntregas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'atividadesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'operacoesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'tiposOperacoesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'frotas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'recomendacoesAdubacao': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'contabil': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},

      // Adicione outros módulos conforme necessário
    },
    'Produtor': <String, Map<String, bool>>{
      'produtores': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'propriedades': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'talhoes': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'itens': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'pessoas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'compras': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosChuvas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'bancos': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      // Adicione outros módulos conforme necessário
      'registrosColetas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosEntregas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'atividadesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'operacoesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'tiposOperacoesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'frotas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'recomendacoesAdubacao': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'contabil': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
    },
    'Gerente': <String, Map<String, bool>>{
      'produtores': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'propriedades': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'talhoes': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'itens': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'pessoas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'compras': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosChuvas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'bancos': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosColetas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosEntregas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'atividadesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'operacoesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'tiposOperacoesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'frotas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'recomendacoesAdubacao': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'contabil': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      // Adicione outros módulos conforme necessário
    },
    'Operador': <String, Map<String, bool>>{
      'produtores': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'propriedades': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'talhoes': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'itens': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'pessoas': <String, bool>{'canView': false, 'canEdit': false, 'canDelete': false},
      'compras': <String, bool>{'canView': false, 'canEdit': false, 'canDelete': false},
      'registrosChuvas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'bancos': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosColetas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'registrosEntregas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'atividadesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'tiposOperacoesRurais': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'frotas': <String, bool>{'canView': true, 'canEdit': true, 'canDelete': true},
      'recomendacoesAdubacao': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'contabil': <String, bool>{'canView': false, 'canEdit': false, 'canDelete': false},
      // Adicione outros módulos conforme necessário
    },
    'Curioso': <String, Map<String, bool>>{
      'produtores': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'propriedades': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'talhoes': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'itens': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'pessoas': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'compras': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'registrosChuvas': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'bancos': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'registrosColetas': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'registrosEntregas': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'atividadesRurais': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'operacoesRurais': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'tiposOperacoesRurais': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'frotas': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'recomendacoesAdubacao': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      'contabil': <String, bool>{'canView': true, 'canEdit': false, 'canDelete': false},
      // Adicione outros módulos conforme necessário
    },
  };
}
