// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77yaq5IgTr7TtP42aO-vi9Q7t2cEY5jw',
    appId: '1:911971151580:android:903849300198ffa5dd8e19',
    messagingSenderId: '911971151580',
    projectId: 'planejacampo',
    storageBucket: 'planejacampo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLg5wChb8EQUZ9U3-yM7x_Ru9RX26sFmE',
    appId: '1:911971151580:ios:3a40a3a618ef0eb2dd8e19',
    messagingSenderId: '911971151580',
    projectId: 'planejacampo',
    storageBucket: 'planejacampo.firebasestorage.app',
    androidClientId: '911971151580-41eg0hftvalrofd7asg1j9gsn3u9amg0.apps.googleusercontent.com',
    iosClientId: '911971151580-u47s7osv0g8h0tn1i2r9mrb22bsp92n5.apps.googleusercontent.com',
    iosBundleId: 'br.com.planejacampo.planejaChuva',
  );
}
