// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbwZC7I7siihvGLQWihWkIbvN316TPk8',
    appId: '1:941184324936:android:4338a3aaf39556fabe8f7d',
    messagingSenderId: '941184324936',
    projectId: 'planejacampodev',
    storageBucket: 'planejacampodev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkg9yjGN_s99PkucIXBopCXUoAeY7svw0',
    appId: '1:941184324936:ios:5792944f546ab666be8f7d',
    messagingSenderId: '941184324936',
    projectId: 'planejacampodev',
    storageBucket: 'planejacampodev.firebasestorage.app',
    androidClientId: '941184324936-433qssj85its98ak63khj51rbsoi90ea.apps.googleusercontent.com',
    iosClientId: '941184324936-vqfbbcu5m9vnffkj8r08ng9sbjlls2o1.apps.googleusercontent.com',
    iosBundleId: 'br.com.planejacampo.planejaDiesel',
  );

}